export const productsData:any = [
    { id: "1" , price : 50 , source: "/product1.jpg", name: "Men's T-Shirt", desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas imperdiet nibh eu commodo scelerisque. Integer sit amet mauris vitae nulla volutpat pharetra vel in orci. Proin tempus, elit a pretium accumsan, velit lectus pulvinar justo, vitae placerat est erat quis elit. Nam in posuere est, sit amet varius sapien. Phasellus consequat quis est non viverra. Sed tristique nisi non convallis ornare. Phasellus scelerisque velit ante, sit amet vehicula mi facilisis vel. Proin ornare velit dolor, malesuada consequat arcu viverra in. Nullam aliquet iaculis nisl, quis mattis sem." },
    { id:"2" , price : 70 , source: "/product2.jpg", name: "Men's Pant" , desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas imperdiet nibh eu commodo scelerisque. Integer sit amet mauris vitae nulla volutpat pharetra vel in orci. Proin tempus, elit a pretium accumsan, velit lectus pulvinar justo, vitae placerat est erat quis elit. Nam in posuere est, sit amet varius sapien. Phasellus consequat quis est non viverra. Sed tristique nisi non convallis ornare. Phasellus scelerisque velit ante, sit amet vehicula mi facilisis vel. Proin ornare velit dolor, malesuada consequat arcu viverra in. Nullam aliquet iaculis nisl, quis mattis sem."},
    { id:"3", price : 150 , source: "/product3.jpg", name: "Men's Shoes",desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas imperdiet nibh eu commodo scelerisque. Integer sit amet mauris vitae nulla volutpat pharetra vel in orci. Proin tempus, elit a pretium accumsan, velit lectus pulvinar justo, vitae placerat est erat quis elit. Nam in posuere est, sit amet varius sapien. Phasellus consequat quis est non viverra. Sed tristique nisi non convallis ornare. Phasellus scelerisque velit ante, sit amet vehicula mi facilisis vel. Proin ornare velit dolor, malesuada consequat arcu viverra in. Nullam aliquet iaculis nisl, quis mattis sem." },
    { id:"4" , price : 250 , source: "/product4.jpg", name: "Men's Watch", desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas imperdiet nibh eu commodo scelerisque. Integer sit amet mauris vitae nulla volutpat pharetra vel in orci. Proin tempus, elit a pretium accumsan, velit lectus pulvinar justo, vitae placerat est erat quis elit. Nam in posuere est, sit amet varius sapien. Phasellus consequat quis est non viverra. Sed tristique nisi non convallis ornare. Phasellus scelerisque velit ante, sit amet vehicula mi facilisis vel. Proin ornare velit dolor, malesuada consequat arcu viverra in. Nullam aliquet iaculis nisl, quis mattis sem." }
  ];

  export const womenProductsData:any = [
    { id: "1" , source: "/product1.jpg", name: "Women's T-Shirt", desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas imperdiet nibh eu commodo scelerisque. Integer sit amet mauris vitae nulla volutpat pharetra vel in orci. Proin tempus, elit a pretium accumsan, velit lectus pulvinar justo, vitae placerat est erat quis elit. Nam in posuere est, sit amet varius sapien. Phasellus consequat quis est non viverra. Sed tristique nisi non convallis ornare. Phasellus scelerisque velit ante, sit amet vehicula mi facilisis vel. Proin ornare velit dolor, malesuada consequat arcu viverra in. Nullam aliquet iaculis nisl, quis mattis sem." },
    { id:"2" , source: "/product2.jpg", name: "Women's Pant" , desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas imperdiet nibh eu commodo scelerisque. Integer sit amet mauris vitae nulla volutpat pharetra vel in orci. Proin tempus, elit a pretium accumsan, velit lectus pulvinar justo, vitae placerat est erat quis elit. Nam in posuere est, sit amet varius sapien. Phasellus consequat quis est non viverra. Sed tristique nisi non convallis ornare. Phasellus scelerisque velit ante, sit amet vehicula mi facilisis vel. Proin ornare velit dolor, malesuada consequat arcu viverra in. Nullam aliquet iaculis nisl, quis mattis sem."},
    { id:"3", source: "/product3.jpg", name: "Women's Shoes",desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas imperdiet nibh eu commodo scelerisque. Integer sit amet mauris vitae nulla volutpat pharetra vel in orci. Proin tempus, elit a pretium accumsan, velit lectus pulvinar justo, vitae placerat est erat quis elit. Nam in posuere est, sit amet varius sapien. Phasellus consequat quis est non viverra. Sed tristique nisi non convallis ornare. Phasellus scelerisque velit ante, sit amet vehicula mi facilisis vel. Proin ornare velit dolor, malesuada consequat arcu viverra in. Nullam aliquet iaculis nisl, quis mattis sem." },
    { id:"4" , source: "/product4.jpg", name: "Women's Watch", desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas imperdiet nibh eu commodo scelerisque. Integer sit amet mauris vitae nulla volutpat pharetra vel in orci. Proin tempus, elit a pretium accumsan, velit lectus pulvinar justo, vitae placerat est erat quis elit. Nam in posuere est, sit amet varius sapien. Phasellus consequat quis est non viverra. Sed tristique nisi non convallis ornare. Phasellus scelerisque velit ante, sit amet vehicula mi facilisis vel. Proin ornare velit dolor, malesuada consequat arcu viverra in. Nullam aliquet iaculis nisl, quis mattis sem." }
  ];